language: ruby
rvm:
 - 2.3.3
 - 2.4.1
 - ruby-head

script:
 - bundle exec rspec

matrix:
  fast_finish: true
  allow_failures:
   - rvm: ruby-head

addons:
  apt:
    packages:
      - libsdl2-dev
      - libsdl2-ttf-dev
      - libpango1.0-dev
      - libgl1-mesa-dev
      - libopenal-dev
      - libsndfile1-dev
      # For Ruby
      - ruby-dev
      - rake
