language: ruby
rvm:
 - 2.3.3
 - 2.4.1
 - ruby-head

before_install:
 - echo "yes" | sudo apt-add-repository ppa:zoogie/sdl2-snapshots
 - sudo apt-get update -qq
 - sudo apt-get install -qq build-essential libsdl2-dev libsdl2-ttf-dev libpango1.0-dev libgl1-mesa-dev libfreeimage-dev libopenal-dev libsndfile-dev
script:
 - bundle exec rspec

matrix:
  fast_finish: true
  allow_failures:
   - rvm: ruby-head
